name: Automatic Activity

on:
  schedule:
    - cron: '30 3 * * *' # Runs daily at 09:00 AM IST (Mumbai Time, 03:30 UTC)
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensure workflow has permission to push commits
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a Change
        run: |
          echo "Last active: $(date)" > activity_log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "armnJs"
          git config --global user.email "armaanshaikh0706@gmail.com"
          git add activity_log.txt
          git commit -m "chore: automatic activity update" || echo "No changes to commit"
          git push
